name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Listar archivos
        run: ls -al
      - name: volver
        run: cd ..
      - name: volver
        run: cd ..
      - name: volver
        run: cd pc        
      - name: volver
        run: cd imagenFront-1
      - name: Construir la imagen Docker
        run: docker build --pull --rm -f Dockerfile -t imagenfront1:latest .
