name: ci

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: List files
        run: ls -al

      - name: Build Docker Image
        run: docker build --pull --rm -t alelu-pellereca/imagenfront1:latest .

      - name: Push Docker Image
        run: docker push alelu-pellereca/imagenfront1:latest